instrumentation:
  default-excludes: true
  excludes: ['**/dist/**', '**/coverage/**']
  include-all-sources: true
  lines: 100
  statements: 100
  functions: 100
  branches: 100
  check-coverage: true
