language: node_js
node_js:
  - "8"
  - "9"
services:
  - docker
install:
  - npm i
before_script:
  - docker run -d --name redis -p 6379:6379 redis:alpine
  - docker run -d --name mongo -p 27017:27017 mongo
after_script:
  - docker rm -f redis
  - docker rm -f mongo
script:
  - npm run test
  - npm run report
