version: '3'
services:
  nginx:
    build: ./nginx
    restart: always
    networks:
      - nodes
    ports:
      - "80:80"
    volumes:
      - "./certs:/etc/nginx/ssl"
      - "./logs:/var/logs"
      - "./public:/var/www"

  redis:
    image: redis:alpine
    restart: always
    ports:
      - "6379"
    networks:
      - databases

  node1:
    build: .
    restart: always
    networks:
      - nodes
      - databases
    ports:
      - "3000"
    volumes:
      - ".:/usr/src/app"
    environment:
      - LOGS_FILE_NAME=./logs/node1.error.log
      - REDIS_HOST=redis

  node2:
    build: .
    restart: always
    networks:
      - nodes
      - databases
    ports:
      - "3000"
    volumes:
      - ".:/usr/src/app"
    environment:
      - LOGS_FILE_NAME=./logs/node2.error.log
      - REDIS_HOST=redis

  node3:
    build: .
    restart: always
    networks:
      - nodes
      - databases
    ports:
      - "3000"
    volumes:
      - ".:/usr/src/app"
    environment:
      - LOGS_FILE_NAME=./logs/node3.error.log
      - REDIS_HOST=redis

networks:
  nodes:

  databases:
