version: '3'
services:
  nginx:
    build: ./nginx
    restart: always
    networks:
      - nodes
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./certs:/etc/nginx/ssl"
      - "./logs:/var/logs"
      - "./dist:/var/www"

  redis:
    image: redis:alpine
    restart: always
    networks:
      - databases

  mongo:
    image: redis:alpine
    restart: always
    networks:
      - databases
    volumes:
      - "./mongo/data:/data/db"

  node1:
    build: .
    restart: always
    networks:
      - nodes
      - databases
    volumes:
      - ".:/usr/src/app"
    environment:
      - LOGS_FILE_NAME=./logs/node1.error.log
      - REDIS_HOST=redis
      - JWT_SECRET=react-awesome-app
      - JWT_TTL=86400000

  node2:
    build: .
    restart: always
    networks:
      - nodes
      - databases
    volumes:
      - ".:/usr/src/app"
    environment:
      - LOGS_FILE_NAME=./logs/node2.error.log
      - REDIS_HOST=redis

  node3:
    build: .
    restart: always
    networks:
      - nodes
      - databases
    volumes:
      - ".:/usr/src/app"
    environment:
      - LOGS_FILE_NAME=./logs/node3.error.log
      - REDIS_HOST=redis

networks:
  nodes:
  databases:
