version: '2'
services:
  nginx:
    build: ./nginx
    restart: always
    links:
        - node1:node1
        - node2:node2
        - node3:node3
    ports:
        - "80:80"

  redis:
    image: redis:alpine
    restart: always
    ports:
        - "6379:6379"

  node1:
    build: .
    restart: always
    links:
        - "redis:redis"
    ports:
        - "3000"
    volumes:
        - ".:/usr/src/app"
  node2:
    build: .
    restart: always
    links:
        - "redis:redis"
    ports:
        - "3000"
    volumes:
        - ".:/usr/src/app"
  node3:
    build: .
    restart: always
    links:
        - "redis:redis"
    ports:
        - "3000"
    volumes:
        - ".:/usr/src/app"
