version: '3'
services:
  nginx:
    build: ./nginx
    restart: always
    networks:
      - nodes
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./certs:/etc/nginx/ssl"
      - "./logs:/var/logs"
      - "./dist:/var/www"

  redis:
    image: redis:alpine
    restart: always
    networks:
      - databases

  mongo:
    image: mongo
    restart: always
    networks:
      - databases
    volumes:
      - "./mongo/data:/data/db"

  node1:
    build: .
    restart: always
    networks:
      - nodes
      - databases
    volumes:
      - "./server:/usr/src/app/server"
      - "./dist:/usr/src/app/dist"
      - "./logs:/var/logs"
    environment:
      - LOGS_FILE_NAME=/var/logs/node1.error.log
      - REDIS_HOST=redis
      - JWT_SECRET=react-awesome-app
      - JWT_TTL=86400000
      - MONGO_URI=mongodb://mongo:27017/users

  node2:
    build: .
    restart: always
    networks:
      - nodes
      - databases
    volumes:
      - "./server:/usr/src/app/server"
      - "./dist:/usr/src/app/dist"
      - "./logs:/var/logs"
    environment:
      - LOGS_FILE_NAME=/var/logs/node2.error.log
      - REDIS_HOST=redis
      - JWT_SECRET=react-awesome-app
      - JWT_TTL=86400000
      - MONGO_URI=mongodb://mongo:27017/users

  node3:
    build: .
    restart: always
    networks:
      - nodes
      - databases
    volumes:
      - "./server:/usr/src/app/server"
      - "./dist:/usr/src/app/dist"
      - "./logs:/var/logs"
    environment:
      - LOGS_FILE_NAME=/var/logs/node3.error.log
      - REDIS_HOST=redis
      - JWT_SECRET=react-awesome-app
      - JWT_TTL=86400000
      - MONGO_URI=mongodb://mongo:27017/users

networks:
  nodes:
  databases:
